name: receivers
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - python-dateutil>=2.9.0
  - progressbar2>=4.0.0
  - requests>=2.31.0
  - rich>=13.0.0
  
  # Development dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-mock>=3.10.0
  - black>=23.0.0
  - ruff>=0.1.0
  - mypy>=1.0.0
  - bandit>=1.7.0
  
  # Documentation
  - mkdocs>=1.5.0
  - mkdocs-material>=9.0.0
  
  # Pip dependencies (not available in conda)
  - pip:
    - mkdocstrings[python]>=0.24.0
    - pytest-xdist>=3.0.0
    # Note: gtimes and gps_parser will be installed separately from local packages