"""Identifiers in dynamic SQL are composed, never string-interpolated (S8).

Table and column names cannot be bound as query parameters, so the two places
that build SQL around caller-supplied names — the EPOS insert/update helpers and
``receivers db drop-station``'s per-table row-count UNION — compose them with
``psycopg2.sql.Identifier`` and let the driver quote them. The inputs are
internal (a config schema, information_schema table names), so this is
defence-in-depth rather than a live injection; these tests keep it that way.

Everything here runs against fake cursors — no PostgreSQL required. A
``sql.Composed`` cannot be rendered to text without a live connection
(``as_string`` needs one), so the assertions inspect the composed tree instead:
the name must appear as an ``Identifier`` node and must NOT appear inside any
literal ``SQL`` fragment.
"""

import argparse
from unittest.mock import patch

from psycopg2 import sql

from receivers.dissemination import epos_db

# A name that would be catastrophic if it were pasted into the statement text.
HOSTILE = 'x"; DROP TABLE rinex_file; --'


def _identifiers(composed) -> list[str]:
    """Every identifier string in a composed statement (depth-first)."""
    out: list[str] = []
    for part in getattr(composed, "seq", []):
        if isinstance(part, sql.Identifier):
            out.extend(part.strings)
        elif isinstance(part, sql.Composed):
            out.extend(_identifiers(part))
    return out


def _sql_text(composed) -> str:
    """Concatenation of the fixed SQL fragments (no identifiers, no values)."""
    chunks: list[str] = []
    for part in getattr(composed, "seq", []):
        if isinstance(part, sql.Composed):
            chunks.append(_sql_text(part))
        elif isinstance(part, sql.SQL):
            chunks.append(part.string)
    return "".join(chunks)


class _FakeCur:
    """Records statements; feeds ``fetchone``/``fetchall`` from queued rows."""

    def __init__(self, ones=(), alls=()):
        self.executed: list[tuple] = []
        self._ones = list(ones)
        self._alls = list(alls)

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False

    def execute(self, stmt, params=None):
        self.executed.append((stmt, params))

    def fetchone(self):
        return self._ones.pop(0) if self._ones else None

    def fetchall(self):
        return self._alls.pop(0) if self._alls else []


class TestEposDbHelperComposition:
    def test_insert_row_composes_table_and_columns(self):
        cur = _FakeCur(ones=[(7,), (7,)])
        assert epos_db.insert_row(cur, "rinex_file", {"name": "A.rnx"}) == 7

        max_stmt, insert_stmt = (s for s, _ in cur.executed)
        assert _identifiers(max_stmt) == ["rinex_file"]
        # id is generated by the helper; name is the caller's column
        assert _identifiers(insert_stmt) == ["rinex_file", "id", "name"]
        # values are bound, not composed
        assert cur.executed[1][1] == [7, "A.rnx"]
        assert "A.rnx" not in _sql_text(insert_stmt)

    def test_insert_row_never_inlines_a_hostile_table_name(self):
        cur = _FakeCur(ones=[(1,), (1,)])
        epos_db.insert_row(cur, HOSTILE, {HOSTILE: "v"})

        for stmt, _ in cur.executed:
            assert HOSTILE not in _sql_text(stmt)
            assert HOSTILE in _identifiers(stmt)

    def test_get_or_create_hit_binds_only_non_null_values(self):
        cur = _FakeCur(ones=[(42,)])
        assert (
            epos_db.get_or_create(
                cur, "agency", {"abbreviation": "ZZ", "id_parent": None}
            )
            == 42
        )

        stmt, params = cur.executed[0]
        assert _identifiers(stmt) == ["agency", "abbreviation", "id_parent"]
        text = _sql_text(stmt)
        assert "IS NULL" in text  # the None column becomes a predicate, not a param
        assert params == ["ZZ"]

    def test_get_or_create_miss_falls_through_to_insert(self):
        cur = _FakeCur(ones=[None, (5,), (5,)])
        assert epos_db.get_or_create(cur, "agency", {"abbreviation": "ZZ"}) == 5
        assert len(cur.executed) == 3  # SELECT, MAX(id), INSERT

    def test_update_row_composes_table_and_set_columns(self):
        cur = _FakeCur()
        epos_db.update_row(cur, "agency", 3, {"name": "Z2", "abbreviation": "ZZ"})

        stmt, params = cur.executed[0]
        assert _identifiers(stmt) == ["agency", "name", "abbreviation"]
        assert params == ["Z2", "ZZ", 3]

    def test_update_row_no_values_is_a_noop(self):
        cur = _FakeCur()
        epos_db.update_row(cur, "agency", 3, {})
        assert cur.executed == []


class _FakeConn:
    def __init__(self, cur):
        self._cur = cur
        self.closed = False

    def cursor(self):
        return self._cur

    def commit(self):
        pass

    def rollback(self):
        pass

    def close(self):
        self.closed = True


class TestDropStationRowCountUnion:
    """The UNION builder emits one Identifier and two bound params per table."""

    def test_union_composes_identifiers_and_pairs_params(self, capsys):
        from receivers.cli import db as cli_db

        tables = ["block_power_status", "file_tracking"]
        cur = _FakeCur(
            ones=[("ELDC",)],  # station-exists probe
            alls=[
                [(t,) for t in tables],  # information_schema lookup
                [("block_power_status", 3), ("file_tracking", 0)],  # counts
            ],
        )
        conn = _FakeConn(cur)

        # db_connection() is the single-host wrapper every ``db`` verb goes through
        with patch.object(cli_db, "db_connection", return_value=conn):
            rc = cli_db.cmd_db_drop_station(
                argparse.Namespace(
                    station_id="eldc", host=None, dry_run=True, force=False
                )
            )
        assert rc == 0

        union_stmt, params = cur.executed[2]
        assert _identifiers(union_stmt) == tables
        # label and sid are bound per branch, in table order — an off-by-one here
        # would only surface against a live DB
        assert params == ("block_power_status", "ELDC", "file_tracking", "ELDC")
        assert "block_power_status" not in _sql_text(union_stmt)
        assert _sql_text(union_stmt).count("UNION ALL") == 1

        out = capsys.readouterr().out
        assert "dry run" in out
        assert conn.closed
